import type { Question } from '@/lib/types';
import {
  Sparkles,
  Heart,
  Landmark,
  Anchor,
  Smile,
  User,
  Users,
  Rabbit,
  Turtle,
  Wallet,
  Coins,
  Gem,
  Backpack,
  CalendarDays,
  Sun,
  Snowflake,
  Mountain,
  Trees,
  Waves,
  Building2,
  Salad,
  Beef,
  Cookie,
  Leaf,
  Bike,
  Swords,
  Ship,
  Train,
  Plane,
  Car,
  HeartPulse,
  BrainCircuit,
  Globe,
  Star,
  Zap,
} from 'lucide-react';

export const questions: Question[] = [
  {
    id: 1,
    key: 'q1',
    question: 'What’s your travel mood right now?',
    options: ['Adventure', 'Relaxation', 'Cultural', 'Romantic', 'Spiritual', 'No preference'],
    icons: [Zap, Anchor, Landmark, Heart, Sparkles, Star],
  },
  {
    id: 2,
    key: 'q2',
    question: 'Travel type?',
    options: ['Solo', 'With partner', 'With family', 'With friends group', 'Flexible', 'No preference'],
    icons: [User, Heart, Users, Users, Smile, Star],
  },
  {
    id: 3,
    key: 'q3',
    question: 'What’s your travel pace?',
    options: ['Fast & Action-Packed', 'Balanced', 'Slow & Relaxing', 'Family-Friendly', 'Immersive', 'No preference'],
    icons: [Rabbit, Plane, Turtle, Users, Landmark, Star],
  },
  {
    id: 4,
    key: 'q4',
    question: 'What is your budget style?',
    options: ['Low (backpacker)', 'Mid-range', 'Premium', 'Luxury', 'Mix of types', 'No preference'],
    icons: [Backpack, Wallet, Coins, Gem, Smile, Star],
  },
  {
    id: 5,
    key: 'q5',
    question: 'How long do you want to travel?',
    options: ['2–3 days', '4–6 days', '1 week', '2 weeks', '1 month', 'Flexible'],
    icons: [CalendarDays, CalendarDays, CalendarDays, CalendarDays, CalendarDays, Star],
  },
  {
    id: 6,
    key: 'q6',
    question: 'Preferred weather?',
    options: ['Hot & Sunny', 'Cold & Snowy', 'Cool Hills', 'Moderate', 'Doesn’t matter'],
    icons: [Sun, Snowflake, Mountain, Trees, Smile, Star],
  },
  {
    id: 7,
    key: 'q7',
    question: 'Favorite scenery?',
    options: ['Beaches', 'Mountains', 'Forests', 'Cities', 'Villages', 'No preference'],
    icons: [Waves, Mountain, Trees, Building2, Landmark, Star],
  },
  {
    id: 8,
    key: 'q8',
    question: 'Preferred food style?',
    options: ['Vegetarian', 'Vegan', 'Non-Vegetarian', 'Street Food Lover', 'Healthy & Clean', 'No preference'],
    icons: [Leaf, Salad, Beef, Cookie, HeartPulse, Star],
  },
  {
    id: 9,
    key: 'q9',
    question: 'Which activities do you like?',
    options: ['Adventure sports', 'Safari/Wildlife', 'Hiking/Trekking', 'Nightlife', 'Beach & Water Fun', 'No preference'],
    icons: [Swords, Trees, Mountain, Bike, Waves, Star],
  },
  {
    id: 10,
    key: 'q10',
    question: 'How do you like to travel around?',
    options: ['Car/Road trip', 'Train', 'Flight', 'Cruise/Ship', 'Mix of all', 'No preference'],
    icons: [Car, Train, Plane, Ship, Smile, Star],
  },
  {
    id: 11,
    key: 'q11',
    question: 'What’s your main goal for this trip?',
    options: ['Adventure', 'Relax & Heal', 'Culture & History', 'Bonding with family/friends', 'Self-discovery', 'No preference'],
    icons: [Zap, HeartPulse, Landmark, Users, BrainCircuit, Star],
  },
  {
    id: 12,
    key: 'q12',
    question: 'Preferred region?',
    options: ['India', 'International', 'Both', 'Nearby only', 'Open to any'],
    icons: [Globe, Globe, Globe, Globe, Globe, Star],
  },
];

export const keyMapping: Record<string, string> = {
  q1: 'travelMood',
  q2: 'travelType',
  q3: 'travelPace',
  q4: 'budgetStyle',
  q5: 'travelDuration',
  q6: 'preferredWeather',
  q7: 'favoriteScenery',
  q8: 'preferredFoodStyle',
  q9: 'likedActivities',
  q10: 'travelAroundPreference',
  q11: 'tripGoal',
  q12: 'preferredRegion',
};
